/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "debugger.pb-c.h"
void   proto__version__init
                     (Proto__Version         *message)
{
  static Proto__Version init_value = PROTO__VERSION__INIT;
  *message = init_value;
}
size_t proto__version__get_packed_size
                     (const Proto__Version *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__version__pack
                     (const Proto__Version *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__version__pack_to_buffer
                     (const Proto__Version *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Version *
       proto__version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Version *)
     protobuf_c_message_unpack (&proto__version__descriptor,
                                allocator, len, data);
}
void   proto__version__free_unpacked
                     (Proto__Version *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__announce_details__init
                     (Proto__AnnounceDetails         *message)
{
  static Proto__AnnounceDetails init_value = PROTO__ANNOUNCE_DETAILS__INIT;
  *message = init_value;
}
size_t proto__announce_details__get_packed_size
                     (const Proto__AnnounceDetails *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__announce_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__announce_details__pack
                     (const Proto__AnnounceDetails *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__announce_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__announce_details__pack_to_buffer
                     (const Proto__AnnounceDetails *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__announce_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__AnnounceDetails *
       proto__announce_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__AnnounceDetails *)
     protobuf_c_message_unpack (&proto__announce_details__descriptor,
                                allocator, len, data);
}
void   proto__announce_details__free_unpacked
                     (Proto__AnnounceDetails *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__announce_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__execution_details__init
                     (Proto__ExecutionDetails         *message)
{
  static Proto__ExecutionDetails init_value = PROTO__EXECUTION_DETAILS__INIT;
  *message = init_value;
}
size_t proto__execution_details__get_packed_size
                     (const Proto__ExecutionDetails *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__execution_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__execution_details__pack
                     (const Proto__ExecutionDetails *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__execution_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__execution_details__pack_to_buffer
                     (const Proto__ExecutionDetails *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__execution_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ExecutionDetails *
       proto__execution_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ExecutionDetails *)
     protobuf_c_message_unpack (&proto__execution_details__descriptor,
                                allocator, len, data);
}
void   proto__execution_details__free_unpacked
                     (Proto__ExecutionDetails *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__execution_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__debug_command__init
                     (Proto__DebugCommand         *message)
{
  static Proto__DebugCommand init_value = PROTO__DEBUG_COMMAND__INIT;
  *message = init_value;
}
size_t proto__debug_command__get_packed_size
                     (const Proto__DebugCommand *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__debug_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__debug_command__pack
                     (const Proto__DebugCommand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__debug_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__debug_command__pack_to_buffer
                     (const Proto__DebugCommand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__debug_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__DebugCommand *
       proto__debug_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__DebugCommand *)
     protobuf_c_message_unpack (&proto__debug_command__descriptor,
                                allocator, len, data);
}
void   proto__debug_command__free_unpacked
                     (Proto__DebugCommand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__debug_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__client_message__init
                     (Proto__ClientMessage         *message)
{
  static Proto__ClientMessage init_value = PROTO__CLIENT_MESSAGE__INIT;
  *message = init_value;
}
size_t proto__client_message__get_packed_size
                     (const Proto__ClientMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__client_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__client_message__pack
                     (const Proto__ClientMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__client_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__client_message__pack_to_buffer
                     (const Proto__ClientMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__client_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ClientMessage *
       proto__client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ClientMessage *)
     protobuf_c_message_unpack (&proto__client_message__descriptor,
                                allocator, len, data);
}
void   proto__client_message__free_unpacked
                     (Proto__ClientMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__client_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__process_info__init
                     (Proto__ProcessInfo         *message)
{
  static Proto__ProcessInfo init_value = PROTO__PROCESS_INFO__INIT;
  *message = init_value;
}
size_t proto__process_info__get_packed_size
                     (const Proto__ProcessInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__process_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__process_info__pack
                     (const Proto__ProcessInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__process_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__process_info__pack_to_buffer
                     (const Proto__ProcessInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__process_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ProcessInfo *
       proto__process_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ProcessInfo *)
     protobuf_c_message_unpack (&proto__process_info__descriptor,
                                allocator, len, data);
}
void   proto__process_info__free_unpacked
                     (Proto__ProcessInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__process_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__function_argument__init
                     (Proto__FunctionArgument         *message)
{
  static Proto__FunctionArgument init_value = PROTO__FUNCTION_ARGUMENT__INIT;
  *message = init_value;
}
size_t proto__function_argument__get_packed_size
                     (const Proto__FunctionArgument *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_argument__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__function_argument__pack
                     (const Proto__FunctionArgument *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_argument__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__function_argument__pack_to_buffer
                     (const Proto__FunctionArgument *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_argument__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FunctionArgument *
       proto__function_argument__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FunctionArgument *)
     protobuf_c_message_unpack (&proto__function_argument__descriptor,
                                allocator, len, data);
}
void   proto__function_argument__free_unpacked
                     (Proto__FunctionArgument *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_argument__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__function_call__init
                     (Proto__FunctionCall         *message)
{
  static Proto__FunctionCall init_value = PROTO__FUNCTION_CALL__INIT;
  *message = init_value;
}
size_t proto__function_call__get_packed_size
                     (const Proto__FunctionCall *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__function_call__pack
                     (const Proto__FunctionCall *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__function_call__pack_to_buffer
                     (const Proto__FunctionCall *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FunctionCall *
       proto__function_call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FunctionCall *)
     protobuf_c_message_unpack (&proto__function_call__descriptor,
                                allocator, len, data);
}
void   proto__function_call__free_unpacked
                     (Proto__FunctionCall *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__function_call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__glfunction__init
                     (Proto__GLFunction         *message)
{
  static Proto__GLFunction init_value = PROTO__GLFUNCTION__INIT;
  *message = init_value;
}
size_t proto__glfunction__get_packed_size
                     (const Proto__GLFunction *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__glfunction__pack
                     (const Proto__GLFunction *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__glfunction__pack_to_buffer
                     (const Proto__GLFunction *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__GLFunction *
       proto__glfunction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__GLFunction *)
     protobuf_c_message_unpack (&proto__glfunction__descriptor,
                                allocator, len, data);
}
void   proto__glfunction__free_unpacked
                     (Proto__GLFunction *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__glfunctions__init
                     (Proto__GLFunctions         *message)
{
  static Proto__GLFunctions init_value = PROTO__GLFUNCTIONS__INIT;
  *message = init_value;
}
size_t proto__glfunctions__get_packed_size
                     (const Proto__GLFunctions *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunctions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__glfunctions__pack
                     (const Proto__GLFunctions *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunctions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__glfunctions__pack_to_buffer
                     (const Proto__GLFunctions *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunctions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__GLFunctions *
       proto__glfunctions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__GLFunctions *)
     protobuf_c_message_unpack (&proto__glfunctions__descriptor,
                                allocator, len, data);
}
void   proto__glfunctions__free_unpacked
                     (Proto__GLFunctions *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__glfunctions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__server_message__init
                     (Proto__ServerMessage         *message)
{
  static Proto__ServerMessage init_value = PROTO__SERVER_MESSAGE__INIT;
  *message = init_value;
}
size_t proto__server_message__get_packed_size
                     (const Proto__ServerMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__server_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__server_message__pack
                     (const Proto__ServerMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__server_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__server_message__pack_to_buffer
                     (const Proto__ServerMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__server_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ServerMessage *
       proto__server_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ServerMessage *)
     protobuf_c_message_unpack (&proto__server_message__descriptor,
                                allocator, len, data);
}
void   proto__server_message__free_unpacked
                     (Proto__ServerMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &proto__server_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__version__field_descriptors[3] =
{
  {
    "major",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__Version, major),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__Version, minor),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__Version, revision),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__version__field_indices_by_name[] = {
  0,   /* field[0] = major */
  1,   /* field[1] = minor */
  2,   /* field[2] = revision */
};
static const ProtobufCIntRange proto__version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__version__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.Version",
  "Version",
  "Proto__Version",
  "proto",
  sizeof(Proto__Version),
  3,
  proto__version__field_descriptors,
  proto__version__field_indices_by_name,
  1,  proto__version__number_ranges,
  (ProtobufCMessageInit) proto__version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__announce_details__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__AnnounceDetails, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__AnnounceDetails, client_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__AnnounceDetails, version),
    &proto__version__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__announce_details__field_indices_by_name[] = {
  1,   /* field[1] = client_name */
  0,   /* field[0] = id */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange proto__announce_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__announce_details__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.AnnounceDetails",
  "AnnounceDetails",
  "Proto__AnnounceDetails",
  "proto",
  sizeof(Proto__AnnounceDetails),
  3,
  proto__announce_details__field_descriptors,
  proto__announce_details__field_indices_by_name,
  1,  proto__announce_details__number_ranges,
  (ProtobufCMessageInit) proto__announce_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue proto__execution_details__operation__enum_values_by_number[6] =
{
  { "CONTINUE", "PROTO__EXECUTION_DETAILS__OPERATION__CONTINUE", 0 },
  { "HALT", "PROTO__EXECUTION_DETAILS__OPERATION__HALT", 1 },
  { "STEP", "PROTO__EXECUTION_DETAILS__OPERATION__STEP", 2 },
  { "TO_SHADER_SWITCH", "PROTO__EXECUTION_DETAILS__OPERATION__TO_SHADER_SWITCH", 3 },
  { "TO_DRAW_CALL", "PROTO__EXECUTION_DETAILS__OPERATION__TO_DRAW_CALL", 4 },
  { "TO_USER_DEFINED", "PROTO__EXECUTION_DETAILS__OPERATION__TO_USER_DEFINED", 5 },
};
static const ProtobufCIntRange proto__execution_details__operation__value_ranges[] = {
{0, 0},{0, 6}
};
const ProtobufCEnumValueIndex proto__execution_details__operation__enum_values_by_name[6] =
{
  { "CONTINUE", 0 },
  { "HALT", 1 },
  { "STEP", 2 },
  { "TO_DRAW_CALL", 4 },
  { "TO_SHADER_SWITCH", 3 },
  { "TO_USER_DEFINED", 5 },
};
const ProtobufCEnumDescriptor proto__execution_details__operation__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "proto.ExecutionDetails.Operation",
  "Operation",
  "Proto__ExecutionDetails__Operation",
  "proto",
  6,
  proto__execution_details__operation__enum_values_by_number,
  6,
  proto__execution_details__operation__enum_values_by_name,
  1,
  proto__execution_details__operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor proto__execution_details__field_descriptors[3] =
{
  {
    "operation",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ExecutionDetails, operation),
    &proto__execution_details__operation__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ExecutionDetails, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ExecutionDetails, call),
    &proto__function_call__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__execution_details__field_indices_by_name[] = {
  2,   /* field[2] = call */
  0,   /* field[0] = operation */
  1,   /* field[1] = thread_id */
};
static const ProtobufCIntRange proto__execution_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__execution_details__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ExecutionDetails",
  "ExecutionDetails",
  "Proto__ExecutionDetails",
  "proto",
  sizeof(Proto__ExecutionDetails),
  3,
  proto__execution_details__field_descriptors,
  proto__execution_details__field_indices_by_name,
  1,  proto__execution_details__number_ranges,
  (ProtobufCMessageInit) proto__execution_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue proto__debug_command__type__enum_values_by_number[22] =
{
  { "DONE", "PROTO__DEBUG_COMMAND__TYPE__DONE", 1 },
  { "CALL_FUNCTION", "PROTO__DEBUG_COMMAND__TYPE__CALL_FUNCTION", 2 },
  { "RECORD_CALL", "PROTO__DEBUG_COMMAND__TYPE__RECORD_CALL", 3 },
  { "CALL_ORIGFUNCTION", "PROTO__DEBUG_COMMAND__TYPE__CALL_ORIGFUNCTION", 4 },
  { "EXECUTE", "PROTO__DEBUG_COMMAND__TYPE__EXECUTE", 5 },
  { "ALLOC_MEM", "PROTO__DEBUG_COMMAND__TYPE__ALLOC_MEM", 6 },
  { "FREE_MEM", "PROTO__DEBUG_COMMAND__TYPE__FREE_MEM", 7 },
  { "READ_RENDER_BUFFER", "PROTO__DEBUG_COMMAND__TYPE__READ_RENDER_BUFFER", 8 },
  { "CLEAR_RENDER_BUFFER", "PROTO__DEBUG_COMMAND__TYPE__CLEAR_RENDER_BUFFER", 9 },
  { "SET_DBG_TARGET", "PROTO__DEBUG_COMMAND__TYPE__SET_DBG_TARGET", 10 },
  { "RESTORE_RENDER_TARGET", "PROTO__DEBUG_COMMAND__TYPE__RESTORE_RENDER_TARGET", 11 },
  { "START_RECORDING", "PROTO__DEBUG_COMMAND__TYPE__START_RECORDING", 12 },
  { "REPLAY", "PROTO__DEBUG_COMMAND__TYPE__REPLAY", 13 },
  { "END_REPLAY", "PROTO__DEBUG_COMMAND__TYPE__END_REPLAY", 14 },
  { "STORE_ACTIVE_SHADER", "PROTO__DEBUG_COMMAND__TYPE__STORE_ACTIVE_SHADER", 15 },
  { "RESTORE_ACTIVE_SHADER", "PROTO__DEBUG_COMMAND__TYPE__RESTORE_ACTIVE_SHADER", 16 },
  { "SET_DBG_SHADER", "PROTO__DEBUG_COMMAND__TYPE__SET_DBG_SHADER", 17 },
  { "GET_SHADER_CODE", "PROTO__DEBUG_COMMAND__TYPE__GET_SHADER_CODE", 18 },
  { "SHADER_STEP", "PROTO__DEBUG_COMMAND__TYPE__SHADER_STEP", 19 },
  { "SAVE_AND_INTERRUPT_QUERIES", "PROTO__DEBUG_COMMAND__TYPE__SAVE_AND_INTERRUPT_QUERIES", 20 },
  { "RESTART_QUERIES", "PROTO__DEBUG_COMMAND__TYPE__RESTART_QUERIES", 21 },
  { "CALL_ORIGFUNCTION_AND_PROCEED", "PROTO__DEBUG_COMMAND__TYPE__CALL_ORIGFUNCTION_AND_PROCEED", 22 },
};
static const ProtobufCIntRange proto__debug_command__type__value_ranges[] = {
{1, 0},{0, 22}
};
const ProtobufCEnumValueIndex proto__debug_command__type__enum_values_by_name[22] =
{
  { "ALLOC_MEM", 5 },
  { "CALL_FUNCTION", 1 },
  { "CALL_ORIGFUNCTION", 3 },
  { "CALL_ORIGFUNCTION_AND_PROCEED", 21 },
  { "CLEAR_RENDER_BUFFER", 8 },
  { "DONE", 0 },
  { "END_REPLAY", 13 },
  { "EXECUTE", 4 },
  { "FREE_MEM", 6 },
  { "GET_SHADER_CODE", 17 },
  { "READ_RENDER_BUFFER", 7 },
  { "RECORD_CALL", 2 },
  { "REPLAY", 12 },
  { "RESTART_QUERIES", 20 },
  { "RESTORE_ACTIVE_SHADER", 15 },
  { "RESTORE_RENDER_TARGET", 10 },
  { "SAVE_AND_INTERRUPT_QUERIES", 19 },
  { "SET_DBG_SHADER", 16 },
  { "SET_DBG_TARGET", 9 },
  { "SHADER_STEP", 18 },
  { "START_RECORDING", 11 },
  { "STORE_ACTIVE_SHADER", 14 },
};
const ProtobufCEnumDescriptor proto__debug_command__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "proto.DebugCommand.Type",
  "Type",
  "Proto__DebugCommand__Type",
  "proto",
  22,
  proto__debug_command__type__enum_values_by_number,
  22,
  proto__debug_command__type__enum_values_by_name,
  1,
  proto__debug_command__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor proto__debug_command__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__DebugCommand, type),
    &proto__debug_command__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__debug_command__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange proto__debug_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__debug_command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.DebugCommand",
  "DebugCommand",
  "Proto__DebugCommand",
  "proto",
  sizeof(Proto__DebugCommand),
  1,
  proto__debug_command__field_descriptors,
  proto__debug_command__field_indices_by_name,
  1,  proto__debug_command__number_ranges,
  (ProtobufCMessageInit) proto__debug_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue proto__client_message__type__enum_values_by_number[6] =
{
  { "ANNOUNCE", "PROTO__CLIENT_MESSAGE__TYPE__ANNOUNCE", 0 },
  { "PROCESS_INFO", "PROTO__CLIENT_MESSAGE__TYPE__PROCESS_INFO", 1 },
  { "GL_FUNCTIONS", "PROTO__CLIENT_MESSAGE__TYPE__GL_FUNCTIONS", 2 },
  { "FUNCTION_CALL", "PROTO__CLIENT_MESSAGE__TYPE__FUNCTION_CALL", 3 },
  { "EXECUTION", "PROTO__CLIENT_MESSAGE__TYPE__EXECUTION", 4 },
  { "DEBUG_COMMAND", "PROTO__CLIENT_MESSAGE__TYPE__DEBUG_COMMAND", 5 },
};
static const ProtobufCIntRange proto__client_message__type__value_ranges[] = {
{0, 0},{0, 6}
};
const ProtobufCEnumValueIndex proto__client_message__type__enum_values_by_name[6] =
{
  { "ANNOUNCE", 0 },
  { "DEBUG_COMMAND", 5 },
  { "EXECUTION", 4 },
  { "FUNCTION_CALL", 3 },
  { "GL_FUNCTIONS", 2 },
  { "PROCESS_INFO", 1 },
};
const ProtobufCEnumDescriptor proto__client_message__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "proto.ClientMessage.Type",
  "Type",
  "Proto__ClientMessage__Type",
  "proto",
  6,
  proto__client_message__type__enum_values_by_number,
  6,
  proto__client_message__type__enum_values_by_name,
  1,
  proto__client_message__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor proto__client_message__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, type),
    &proto__client_message__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, has_thread_id),
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "announce",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, announce),
    &proto__announce_details__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "execution",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, execution),
    &proto__execution_details__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ClientMessage, command),
    &proto__debug_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__client_message__field_indices_by_name[] = {
  3,   /* field[3] = announce */
  5,   /* field[5] = command */
  4,   /* field[4] = execution */
  1,   /* field[1] = id */
  2,   /* field[2] = thread_id */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange proto__client_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor proto__client_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ClientMessage",
  "ClientMessage",
  "Proto__ClientMessage",
  "proto",
  sizeof(Proto__ClientMessage),
  6,
  proto__client_message__field_descriptors,
  proto__client_message__field_indices_by_name,
  1,  proto__client_message__number_ranges,
  (ProtobufCMessageInit) proto__client_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__process_info__field_descriptors[4] =
{
  {
    "executable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ProcessInfo, executable),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ProcessInfo, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is64bit",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ProcessInfo, is64bit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Proto__ProcessInfo, n_thread_id),
    PROTOBUF_C_OFFSETOF(Proto__ProcessInfo, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__process_info__field_indices_by_name[] = {
  0,   /* field[0] = executable */
  2,   /* field[2] = is64bit */
  1,   /* field[1] = pid */
  3,   /* field[3] = thread_id */
};
static const ProtobufCIntRange proto__process_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__process_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ProcessInfo",
  "ProcessInfo",
  "Proto__ProcessInfo",
  "proto",
  sizeof(Proto__ProcessInfo),
  4,
  proto__process_info__field_descriptors,
  proto__process_info__field_indices_by_name,
  1,  proto__process_info__number_ranges,
  (ProtobufCMessageInit) proto__process_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__function_argument__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__FunctionArgument, type),
    &proto__debug_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__FunctionArgument, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__FunctionArgument, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__function_argument__field_indices_by_name[] = {
  1,   /* field[1] = address */
  2,   /* field[2] = data */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange proto__function_argument__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__function_argument__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FunctionArgument",
  "FunctionArgument",
  "Proto__FunctionArgument",
  "proto",
  sizeof(Proto__FunctionArgument),
  3,
  proto__function_argument__field_descriptors,
  proto__function_argument__field_indices_by_name,
  1,  proto__function_argument__number_ranges,
  (ProtobufCMessageInit) proto__function_argument__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__function_call__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, has_thread_id),
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, thread_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, has_return_type),
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, return_type),
    &proto__debug_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_data",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, has_return_data),
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, return_data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arguments",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, n_arguments),
    PROTOBUF_C_OFFSETOF(Proto__FunctionCall, arguments),
    &proto__function_argument__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__function_call__field_indices_by_name[] = {
  4,   /* field[4] = arguments */
  0,   /* field[0] = name */
  3,   /* field[3] = return_data */
  2,   /* field[2] = return_type */
  1,   /* field[1] = thread_id */
};
static const ProtobufCIntRange proto__function_call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor proto__function_call__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FunctionCall",
  "FunctionCall",
  "Proto__FunctionCall",
  "proto",
  sizeof(Proto__FunctionCall),
  5,
  proto__function_call__field_descriptors,
  proto__function_call__field_indices_by_name,
  1,  proto__function_call__number_ranges,
  (ProtobufCMessageInit) proto__function_call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__glfunction__field_descriptors[8] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, prefix),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, extname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_debuggable",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, is_debuggable),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "primitive_mode_index",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, primitive_mode_index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_shader_switch",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, is_shader_switch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_frame_end",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, is_frame_end),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_framebuffer_change",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__GLFunction, is_framebuffer_change),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__glfunction__field_indices_by_name[] = {
  1,   /* field[1] = extname */
  3,   /* field[3] = is_debuggable */
  6,   /* field[6] = is_frame_end */
  7,   /* field[7] = is_framebuffer_change */
  5,   /* field[5] = is_shader_switch */
  2,   /* field[2] = name */
  0,   /* field[0] = prefix */
  4,   /* field[4] = primitive_mode_index */
};
static const ProtobufCIntRange proto__glfunction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor proto__glfunction__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.GLFunction",
  "GLFunction",
  "Proto__GLFunction",
  "proto",
  sizeof(Proto__GLFunction),
  8,
  proto__glfunction__field_descriptors,
  proto__glfunction__field_indices_by_name,
  1,  proto__glfunction__number_ranges,
  (ProtobufCMessageInit) proto__glfunction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__glfunctions__field_descriptors[1] =
{
  {
    "function",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Proto__GLFunctions, n_function),
    PROTOBUF_C_OFFSETOF(Proto__GLFunctions, function),
    &proto__glfunction__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__glfunctions__field_indices_by_name[] = {
  0,   /* field[0] = function */
};
static const ProtobufCIntRange proto__glfunctions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__glfunctions__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.GLFunctions",
  "GLFunctions",
  "Proto__GLFunctions",
  "proto",
  sizeof(Proto__GLFunctions),
  1,
  proto__glfunctions__field_descriptors,
  proto__glfunctions__field_indices_by_name,
  1,  proto__glfunctions__number_ranges,
  (ProtobufCMessageInit) proto__glfunctions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const Proto__ErrorCode proto__server_message__error_code__default_value = PROTO__ERROR_CODE__NONE;
static const ProtobufCFieldDescriptor proto__server_message__field_descriptors[6] =
{
  {
    "error_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, error_code),
    &proto__error_code__descriptor,
    &proto__server_message__error_code__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function_call",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, n_function_call),
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, function_call),
    &proto__function_call__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gl_functions",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, gl_functions),
    &proto__glfunctions__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proc_info",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Proto__ServerMessage, proc_info),
    &proto__process_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__server_message__field_indices_by_name[] = {
  0,   /* field[0] = error_code */
  3,   /* field[3] = function_call */
  4,   /* field[4] = gl_functions */
  1,   /* field[1] = id */
  2,   /* field[2] = message */
  5,   /* field[5] = proc_info */
};
static const ProtobufCIntRange proto__server_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor proto__server_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ServerMessage",
  "ServerMessage",
  "Proto__ServerMessage",
  "proto",
  sizeof(Proto__ServerMessage),
  6,
  proto__server_message__field_descriptors,
  proto__server_message__field_indices_by_name,
  1,  proto__server_message__number_ranges,
  (ProtobufCMessageInit) proto__server_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue proto__debug_type__enum_values_by_number[18] =
{
  { "CHAR", "PROTO__DEBUG_TYPE__CHAR", 0 },
  { "UNSIGNED_CHAR", "PROTO__DEBUG_TYPE__UNSIGNED_CHAR", 1 },
  { "SHORT", "PROTO__DEBUG_TYPE__SHORT", 2 },
  { "UNSIGNED_SHORT", "PROTO__DEBUG_TYPE__UNSIGNED_SHORT", 3 },
  { "INT", "PROTO__DEBUG_TYPE__INT", 4 },
  { "UNSIGNED_INT", "PROTO__DEBUG_TYPE__UNSIGNED_INT", 5 },
  { "LONG_INT", "PROTO__DEBUG_TYPE__LONG_INT", 6 },
  { "UNSIGNED_LONG_INT", "PROTO__DEBUG_TYPE__UNSIGNED_LONG_INT", 7 },
  { "LONG_LONG_INT", "PROTO__DEBUG_TYPE__LONG_LONG_INT", 8 },
  { "UNSIGNED_LONG_LONG_INT", "PROTO__DEBUG_TYPE__UNSIGNED_LONG_LONG_INT", 9 },
  { "FLOAT", "PROTO__DEBUG_TYPE__FLOAT", 10 },
  { "DOUBLE", "PROTO__DEBUG_TYPE__DOUBLE", 11 },
  { "LONGDOUBLE", "PROTO__DEBUG_TYPE__LONGDOUBLE", 12 },
  { "POINTER", "PROTO__DEBUG_TYPE__POINTER", 13 },
  { "STRUCT", "PROTO__DEBUG_TYPE__STRUCT", 14 },
  { "BITFIELD", "PROTO__DEBUG_TYPE__BITFIELD", 15 },
  { "ENUM", "PROTO__DEBUG_TYPE__ENUM", 16 },
  { "BOOL", "PROTO__DEBUG_TYPE__BOOL", 17 },
};
static const ProtobufCIntRange proto__debug_type__value_ranges[] = {
{0, 0},{0, 18}
};
const ProtobufCEnumValueIndex proto__debug_type__enum_values_by_name[18] =
{
  { "BITFIELD", 15 },
  { "BOOL", 17 },
  { "CHAR", 0 },
  { "DOUBLE", 11 },
  { "ENUM", 16 },
  { "FLOAT", 10 },
  { "INT", 4 },
  { "LONGDOUBLE", 12 },
  { "LONG_INT", 6 },
  { "LONG_LONG_INT", 8 },
  { "POINTER", 13 },
  { "SHORT", 2 },
  { "STRUCT", 14 },
  { "UNSIGNED_CHAR", 1 },
  { "UNSIGNED_INT", 5 },
  { "UNSIGNED_LONG_INT", 7 },
  { "UNSIGNED_LONG_LONG_INT", 9 },
  { "UNSIGNED_SHORT", 3 },
};
const ProtobufCEnumDescriptor proto__debug_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "proto.DebugType",
  "DebugType",
  "Proto__DebugType",
  "proto",
  18,
  proto__debug_type__enum_values_by_number,
  18,
  proto__debug_type__enum_values_by_name,
  1,
  proto__debug_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue proto__error_code__enum_values_by_number[5] =
{
  { "NONE", "PROTO__ERROR_CODE__NONE", 0 },
  { "HEADER_MISMATCH", "PROTO__ERROR_CODE__HEADER_MISMATCH", 1 },
  { "VERSION_MISMATCH", "PROTO__ERROR_CODE__VERSION_MISMATCH", 2 },
  { "AUTH_FAILED", "PROTO__ERROR_CODE__AUTH_FAILED", 3 },
  { "GENERIC_ERROR", "PROTO__ERROR_CODE__GENERIC_ERROR", 4 },
};
static const ProtobufCIntRange proto__error_code__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex proto__error_code__enum_values_by_name[5] =
{
  { "AUTH_FAILED", 3 },
  { "GENERIC_ERROR", 4 },
  { "HEADER_MISMATCH", 1 },
  { "NONE", 0 },
  { "VERSION_MISMATCH", 2 },
};
const ProtobufCEnumDescriptor proto__error_code__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "proto.ErrorCode",
  "ErrorCode",
  "Proto__ErrorCode",
  "proto",
  5,
  proto__error_code__enum_values_by_number,
  5,
  proto__error_code__enum_values_by_name,
  1,
  proto__error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
