#ifndef DBG_TYPE_H
#define DBG_TYPE_H

#include <stdlib.h>

enum DBG_TYPE {
	DBG_TYPE_CHAR = 0,
	DBG_TYPE_UNSIGNED_CHAR,
	DBG_TYPE_SHORT_INT,
	DBG_TYPE_UNSIGNED_SHORT_INT,
	DBG_TYPE_INT,
	DBG_TYPE_UNSIGNED_INT,
	DBG_TYPE_LONG_INT,
	DBG_TYPE_UNSIGNED_LONG_INT,
	DBG_TYPE_LONG_LONG_INT,
	DBG_TYPE_UNSIGNED_LONG_LONG_INT,
	DBG_TYPE_FLOAT,
	DBG_TYPE_DOUBLE,
	DBG_TYPE_LONG_DOUBLE,
	DBG_TYPE_POINTER,
	DBG_TYPE_STRUCT,
	DBG_TYPE_BITFIELD,
	DBG_TYPE_ENUM,
	DBG_TYPE_BOOLEAN
};

size_t sizeof_dbg_type(enum DBG_TYPE d);
void print_dbg_type(enum DBG_TYPE d, const void* buf);

#endif